version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: movies-reviews-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=movies-reviews
    volumes:
      - mongodb_data:/data/db
    command: mongod --auth

volumes:
  mongodb_data: 