version: '3.8' # Specify the Docker Compose file format version

services:
  mongodb:
    image: mongo:latest # Use the latest official MongoDB image
    container_name: movies-reviews-mongodb # Name the MongoDB container
    ports:
      - "27017:27017" # Map host port 27017 to container port 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin # Set MongoDB root username
      - MONGO_INITDB_ROOT_PASSWORD=password123 # Set MongoDB root password
      - MONGO_INITDB_DATABASE=movies-reviews # Set default database to create
    volumes:
      - mongodb_data:/data/db # Persist MongoDB data on the host
    command: mongod --auth # Start MongoDB with authentication enabled

volumes:
  mongodb_data: # Define a named volume for MongoDB data persistence